.TH TODU 1 "Mai 2024" "Version 1.0"
.SH NAME
todu \- simple command-line todo list manager
.SH SYNOPSIS
.B todu
.RB [ add
.IR text ]
.RB [ del
.IR id/all ]
.RB [ done
.IR id/all ]
.RB [ undone
.IR id/all ]
.SH DESCRIPTION
.B todu
is a simple command-line utility for managing a todo list. 
It allows to add, list, mark as complete, and remove tasks from their todo list.
.SH OPTIONS
.TP
.BI add    " text"
Add a new task to the todo list.
.TP
.BI del    " id/all"
Remove a task from the todo list.
.TP
.BI done   " id/all"
Mark a task as complete.
.TP
.BI undone " id/all"
Mark a task as not finished.
.SH AUTHOR
.IR todu
was wriiten by Bogdan. More at <https://github.com/snowsova/todu>


